import { Montserrat } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/utils/Provider";
import Navbar from "@/component/Navbar";
import DiscountBar from "@/component/DiscountBar";
import Footer from "@/component/Footer";

const monserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={monserrat.className}>
        <ReactQueryProvider>
          <DiscountBar />
          <Navbar />
          <div className="global_padding">{children}</div>
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
